project_name: football_player_auto_embed

id_column: version_id

vector_store:
  vector_collection_name: dab
  metadata_columns:
    - category
    - make
    - model
    - commercial_model
    - version
    - trim_level
    - gearbox
    - energy


data:
  training:
    type: csv
    path: data/dab/dab-last-versions.csv
  prediction:
    type: csv
    path: data/dab/dab-last-versions.csv

modeling:
  model_version: latest
  light_mode: false
  light_mode_sample_size: 15000
  bottle_neck_size: 32
  epochs: 5
  batch_size: 128
  hidden_layer_sizes: [256, 128, 64]
  modeling_columns:
    categorical_columns:
      - category
      - make
      - model
      - commercial_model
      - version
      - trim_level
      - gearbox
      - energy

visualisation:
  n_samples: 15000
  visualisation_columns:
    hover_data_columns_name:
      - category
      - make
      - model
      - commercial_model
      - version
      - trim_level
      - gearbox
      - energy
    color_data_column_name: version
